# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb28d0bef3e8ec5bd46b67836ff620be19db2febd94e507d01d61c5bc712029ecf3a476546a7ad5d85c00bc0f830cb75c9e341eb690ec36cf0b72130110d743e

test:
  secret_key_base: 0c7997739ad295337dc5220e1d28b6730d9b45248fc6807f7c89956fda988d6788c9e93251e86c33c4ec6fed8233e35b3d8ffa3f5e5f66bb17923f0cd72499ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
